// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkdY8iGyg_Znf5cHRnI_OpuJk4g03DvoM',
    appId: '1:755601845400:web:c5c8ec8a84da8b299a34ed',
    messagingSenderId: '755601845400',
    projectId: 'to-do-c7e29',
    authDomain: 'to-do-c7e29.firebaseapp.com',
    storageBucket: 'to-do-c7e29.appspot.com',
    measurementId: 'G-T94C30M0Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkb2e7zQ73tO2_S2TKZcryFefIBs9JaM',
    appId: '1:755601845400:android:94fe8497cdb1d87d9a34ed',
    messagingSenderId: '755601845400',
    projectId: 'to-do-c7e29',
    storageBucket: 'to-do-c7e29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAte-fDDlrSnRM9nkANIQYoNuSsOnoeCRo',
    appId: '1:755601845400:ios:706a045376b1263d9a34ed',
    messagingSenderId: '755601845400',
    projectId: 'to-do-c7e29',
    storageBucket: 'to-do-c7e29.appspot.com',
    iosBundleId: 'com.example.todoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAte-fDDlrSnRM9nkANIQYoNuSsOnoeCRo',
    appId: '1:755601845400:ios:706a045376b1263d9a34ed',
    messagingSenderId: '755601845400',
    projectId: 'to-do-c7e29',
    storageBucket: 'to-do-c7e29.appspot.com',
    iosBundleId: 'com.example.todoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkdY8iGyg_Znf5cHRnI_OpuJk4g03DvoM',
    appId: '1:755601845400:web:34e8ecd73f7c72499a34ed',
    messagingSenderId: '755601845400',
    projectId: 'to-do-c7e29',
    authDomain: 'to-do-c7e29.firebaseapp.com',
    storageBucket: 'to-do-c7e29.appspot.com',
    measurementId: 'G-WQESM2XZ6S',
  );

}